id: ID3D09664
legacy_id: P009195
ocr_import_info:
  bdrc_scan_id: W1EE16
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T21:09:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:41:25.752591+00:00'
last_modified: 2022-08-31 03:41:35.803884
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1EE16
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1EE16
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཕགས་པ་གསེར་འོད་དམ་པའི་མདོ།（སོག་ཡིག）
statistics:
  ocr_word_mean_confidence_index: 0.5911820779326968
  ocr_word_median_confidence_index: 0.6100000143051147
quality: null
bases:
  I1KG16968:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16968
      total_pages: 122
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG16968.txt
    statistics:
      ocr_word_median_confidence_index: 0.6100000143051147
      ocr_word_mean_confidence_index: 0.5911820779326968
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
