id: P009195
initial_creation_type: ocr
source_metadata:
  id: bdr:W1EE16
  title: འཕགས་པ་གསེར་འོད་དམ་པའི་མདོ།（སོག་ཡིག）
  author: ''
  volumes:
    ad7caabf2c4b417aae31ad1f9c4be3d4:
      image_group_id: I1KG16968
      title: ''
      volume_number: 1
      total_pages: 122
      base_file: v001.txt
